### ISSUE TITLE
Make WiFi connect to Ad-hoc networks.

### ISSUE THREAD

**Issue by ghost** [gsstudios/Dorimanx-SG2-I9100-Kernel#11]
It would be great to connect to the networks created with the WiFi cards from Notebooks that don't support Master/AP mode and work on Ad-hoc mode only, wich I belive it is a mayority, without the need for a router/repeater.

**Comment by gsstudios** [comment]
Is this a feature available on other kernels or ROMs?

**Comment by ghost** [comment]
[In this thread](http://forum.xda-developers.com/nexus-s/help/solved-how-to-connect-to-ad-hoc-ibss-t1591207/page4) are two methods:
1- From the OP who tells to replace a the wpa_supplicant file.
2- One of the comentaries tell to just modify the wpa_supplicant.conf file wich is restored on every manual scan, wich I think it's safer.

**Comment by ghost** [comment]
Not that I know of. I searched a couple of years ago and the method of changing wpa_supplicant file sounded a bit unstable. Now I found the new info on modifying the .conf file wich sounds promessing.

**Comment by ghost** [comment]
I believe that the network has to be encripted, wep or wpa2 maybe for the method that changes the .conf file to work properly.

**Comment by gsstudios** [comment]
Following your XDA post, I've updated wifi drivers to bring us a step closer in adding this feature.

**Comment by ghost** [comment]
Great, man!
Here its a most interesting info
http://thinktube.com/index.php/tech-en/android/wifi-ibss
I believe they are the creators of the patchs.

Here they are implemented on a AOKP rom project
http://gerrit.aokp.co/#/q/ad%20hoc
The latest one ads them to LP

This I use to test the connectiviy thru Terminal as it install iwconfig and other usefull binaries.
http://bcmon.blogspot.com.ar/2012/09/working-monitor-mode-on-nexus-one.html
http://code.google.com/p/bcmon/
It works on nexus phones too as they have similar wifi chipsets as S2.

Here is also iw, another port from linuxs network tools for terminal.
http://www.onlyxool.net/wp-content/uploads/2012/06/iw.tar.gz
http://www.onlyxool.net/porting-iw-tools-to-android/

commands to test connection:

create ad-hoc
su
ip link set dev wlan0 down
iwconfig wlan0 mode ad-hoc
iwconfig wlan0 channel 6
iwconfig wlan0 essid 'Test1'
ip link set dev wlan0 up
ifconfig wlan0 192.168.65.129

connect to ad-hoc
su
iwconfig wlan0 mode ad-hoc
iwconfig wlan0 channel 6
iwconfig wlan0 essid 'Test1'

The commands above can be used on android terminal and on linux terminal aswell.
with sudo or su ping followed with ip address tests the connection, like:
ping 192.168.65.129

I think markox89 did some work on his cm11 rom related to this with help from gustavos but i do not seem to find the link right now. but I believe it was with and old wifi driver they were updating.

I share some other things when I can.
Thanks for working on this man.
Regards.

**Comment by gsstudios** [comment]
i think all main required patches to make IBSS mode (Ad-hoc) was already included with new wifi driver. So now we just need to debug to see what's to root cause

**Comment by ghost** [comment]
Ok. I'll try to find a propper way to debug it. Maybe has something to do
with ip becose on DHCP it does nothing but with static it at least try to
connect a while until it fails, like it sudenly recongnices the network as
ad-hoc and refuses to connect. I'm realky axious to see some logs or
debugging but my hdd died and im runing linux from a 4gb pendrive with 0
space left.
Is there a way to see some live wifi logging from within android?
Regards.

**Comment by gsstudios** [comment]
I'm not too sure if we can get live wifi logging. (I don't know any way to).

**Comment by ghost** [comment]
I found some tools for live logging on the repository of F-Droid app. I just have to learn how to use them properly and read logs.

Here http://thinktube.com/index.php/tech-en/android/wifi-ibss says that Nexus 7 works well with ad-hocs on cm12. I see that it has the same wifi chipset that our I9100. Could the wifi drivers for the Nexus 7 work for the S2? or at least maybe give some clues.

**Comment by gsstudios** [comment]
I have done all of the other changes in the .patch that wasn't applied to the config file yet (last time, only the main line was added). I hope it should work after the next build.

**Comment by gsstudios** [comment]
I think I will have to abandon this feature request since I believe I will create more issues than make the kernel any better.
