### ISSUE TITLE
Bluetooth Tether from WiFi network instead of normal 2g/3g network.

### ISSUE THREAD

**Issue by ghost** [gsstudios/Dorimanx-SG2-I9100-Kernel#12]
I don't know if this is even posible with the hardware of our I9100. But sharing this way would open up very much interesting posibilities. One being for the S2 to act as a repeater.

**Comment by gsstudios** [comment]
I don't think it is possible for kernel to do this.

**Comment by ghost** [comment]
yeah, I knew that the WiFi/Bluetooth chip it a composed one with the two functions, so probably  its a hardware limitation. Thanks anyway :+1:

**Comment by ghost** [comment]
¡¡¡Good news¡¡¡ it seems this always worked out of the box. I guess i got confused with so many new and old divices in my hands...
Just that the bluetooth signal isn't that stong using this mode.
Now I recently saw an option in the developer options/menu of the RR-Lp rom, wich seem to restore strengh to wifi in normal tethering. I wonder what effect will it have in this mode.
Sorry for the inconvenience. thanks.
