### ISSUE TITLE
Zipalign from Stweaks deletes simlinks to apps

### ISSUE THREAD

**Issue by ghost** [gsstudios/Dorimanx-SG2-I9100-Kernel#14]
I believe it has to do with something relative to permission management as it changes permission to the folders of the apps on /data/app. The apps are fixed by de system after wiping cache wich i think relinks them back.

**Comment by gsstudios** [comment]
https://github.com/gsstudios/initramfs3/commit/b8185af6975b76c13424d4e9c40550a58ac8b18d

According to DorimanX, zipalign only works on dalvik. ART doesn't support this function causing this problem described above. This also fixes a nasty bug on performance profiles.
