### ISSUE TITLE
Ext4 is not mounting properly

### ISSUE THREAD

**Issue by gsstudios** [gsstudios/Dorimanx-SG2-I9100-Kernel#2]
Ext4 needs to be fixed in dorimanx kernel. I believe it is to do with the init commits.

**Comment by gsstudios** [comment]
@computoncio @ataliba @stantrc @dorimanx @chhapil @stelistcristi 

hi other devs and former devs of dorimanx kernel of the s2, I'm trying to solve the problem where ext4 is not mounting. I'm pretty sure most of the code required has already been included in the kernel, but there is something missing that is preventing people from mounting their internal and external sd cards. 

If you guys have time, could you please have a look at the code? StanTRC was already informed on this issue but still there is no progression towards solving this issue.

Regards, gsstudios.

**Comment by StanTRC** [comment]
where is your logs?

**Comment by gsstudios** [comment]
I will ask people on XDA if they can provide logs since my internal and external storage are formatted as fat32

**Comment by gsstudios** [comment]
Here are some logs: http://forum.xda-developers.com/showpost.php?p=61976201&postcount=243

**Comment by gsstudios** [comment]
@computoncio, could you please help me look into this issue. 

thanks.

**Comment by Realex-fire** [comment]
It seems that this is now fixed. My ext4 sd card is mounted in cm13.

**Comment by gsstudios** [comment]
Thanks for letting me know. I still need to test if my internal storage runs fine on ext4 before closing this commit :)

**Comment by gsstudios** [comment]
Yep. Ext4 is running fine on my internal sd card. Once again, I'll have to test on LP as well but I believe this should be solved. 
Edit: I shall test the stability for a little longer and will report back. Main bug fixed though :)

**Comment by Realex-fire** [comment]
I found a new bug:
if at first to launch cm13, then to reboot in recovery and to mount ext4 partitions to PC, then it is possible to find out that the owner and group on the partition changed on 1023, and permissions 775 are set what to lead to impossibility of record of files on the partition without change of the owner.
We need to find the reason, it or cm13 or a kernel.
