### ISSUE TITLE
Selinux needs to be permissive for MM kernel to work

### ISSUE THREAD

**Issue by gsstudios** [gsstudios/Dorimanx-SG2-I9100-Kernel#23]
Selinux disabled messes up a lot of things in Marshmallow. Marshmallow needs at least selinux permissive to be functional. 

Thanks to @realex-fire, kernel compiles with selinux, but this breaks the loading of the kernel :(

**Current problems with selinux disabled** 
- Vold relies on setexeccon which requires selinux to be enabled. 
- Probably many other things because of stricter policies in CM13

**Current problems with selinux enabled**
- Breaks loading of kernel

**What's working**
- Recovery

**ETA:** Unknown

ofc, any help is welcomed :)

**Comment by gsstudios** [comment]
Selinux-enable branch was created to address selinux issues

**Comment by gsstudios** [comment]
@chhapil @realex-fire 

Do you guys know how to debug this:

security/security.c: In function ‘security_inode_init_security’:
security/security.c:364:7: warning: passing argument 4 of ‘security_ops->inode_init_security’ from incompatible pointer type
       &lsm_xattr->name,
       ^
security/security.c:364:7: note: expected ‘char *_’ but argument is of type ‘const char *_’ - note from me: This is with double asterisks, not single!
security/security.c: In function ‘security_tun_dev_attach’:
security/security.c:1305:9: error: too few arguments to function ‘security_ops->tun_dev_attach’
  return security_ops->tun_dev_attach(sk);
         ^
security/security.c:1306:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
I fixed all other warnings already, but can't get past these errors. 

Thanks

**Comment by chhapil** [comment]
Somewhere the char variable is defined as const, either in function
declaration or while defining the variable.
You may have to remove const keyword

**Comment by gsstudios** [comment]
Selinux work will be discontinued for a bit. Will need to spend time fixing other bugs before solving this :)

**Comment by gsstudios** [comment]
Selinux is now working and is set to permissive :)
