### ISSUE TITLE
advanced support for F2FS 

### ISSUE THREAD

**Issue by gsstudios** [gsstudios/Dorimanx-SG2-I9100-Kernel#34]
**Status:** F2FS partitions mount, but we need to fix the init system to properly support F2FS. 

**Things to do:**
- Modify init script to run fsck.f2fs on f2fs partitions
- Remove false errors where data partition needs to be fixed 

**ETA:** Unknown

**Comment by gsstudios** [comment]
I'm pretty sure ROM must support F2FS before you can boot with F2FS. It's best to wait until there are some CM12.1 roms that support this soon before moving on to CM13.

**Comment by gsstudios** [comment]
I have now merged f2fs up to what the kernel can allow. It seems were are missing a few changes in order to update further. We're basically using linux kernel 3.16+ f2fs which does have lots of fixes we can take advantage of. Will test soon on CM13.

**Comment by Realex-fire** [comment]
I think that it is better to rename this issue into advanced support f2fs as basic functions work well.

**Comment by Realex-fire** [comment]
https://github.com/Realex-fire/initramfs3/commit/5aceac7fd89a0504507ecdab1f7ed9fbebc4d3e0 - Now it should work, but it should be checked. Now the partitions /data and /cache also can be formatted into f2fs.

**Comment by Realex-fire** [comment]
Have you checked this ? Potentially this should work, but I'm not sure.

**Comment by gsstudios** [comment]
I haven't tested it yet. So far, there is no issue with other file systems, so I will have to switch to F2FS to find out later.

**Comment by gsstudios** [comment]
I will test out f2fs soon with the latest changes.

**Comment by gsstudios** [comment]
Works well. I shall test a bit more before releasing.

**Comment by gsstudios** [comment]
Only problem is that I still get the error log file on boot because it doesn't detect /cache and /data as ext4.

**Comment by Realex-fire** [comment]
Everything is normal. File system is detected. The log will be created after each loading because partitions are checked for existence of mistakes every time.
You can be convinced of it. /tmp/data_fs_check - here recorded file system on data partition.

**Comment by Realex-fire** [comment]
Still some completions of init script are necessary, I will make it soon.

**Comment by Realex-fire** [comment]
@gsstudios,
https://github.com/Realex-fire/initramfs3/commit/3b9ccc36c0f8de340f98dcaf3b8665c2400ca695 - check it again, now it should work.

**Comment by gsstudios** [comment]
Thanks. I will test soon.
