### ISSUE TITLE
Launcher and System UI FCs

### ISSUE THREAD

**Issue by gsstudios** [gsstudios/Dorimanx-SG2-I9100-Kernel#35]
@chhapil @kularny

There has been occasional launcher and System UI FCs happening in LP. 

Areas of interest:
- Lowmemorykiller: Possible system services are not properly protected from OOM, so it is being killed by OOM - Correct me if I'm wrong
- VM settings is killing the process ??? There may be some form of corruption happening.

Cause: Unknown 

Possible workarounds:
- When using Nova Launcher, enable aggressive desktop in the settings

**Comment by gsstudios** [comment]
Here is some logs kindly provided by Skyline: http://forum.xda-developers.com/showpost.php?p=65403303&postcount=859

**Comment by gsstudios** [comment]
Main commit:
https://github.com/gsstudios/Dorimanx-SG2-I9100-Kernel/commit/4cca3f4a36e3d381fa7f61e49d04d917a3cc8e57

OOM avoid kill processes (our kernel):
https://github.com/gsstudios/Dorimanx-SG2-I9100-Kernel/blob/master-lp/drivers/staging/android/lowmemorykiller.c#L93

OOM avoid kill processes (LG G2 LP kernel):
https://github.com/dorimanx/DORIMANX_LG_STOCK_LP_KERNEL/blob/master/drivers/staging/android/lowmemorykiller.c#L227

Related XDA post:
 http://forum.xda-developers.com/galaxy-s2/development-derivatives/kernel-3-12-rc6-dorimanx-8-43-jb-i9100-t1617219/post42648016#post42648016

**Comment by gsstudios** [comment]
The weird thing is that LG G2 kernel freely allows OOM to kill system processes in LP, whereas our kernel still avoids doing so. 

OOM avoid kill processes (LP G2 LP kernel):
https://github.com/dorimanx/DORIMANX_LG_STOCK_LP_KERNEL/blob/master/drivers/staging/android/lowmemorykiller.c#L244
https://github.com/dorimanx/DORIMANX_LG_STOCK_LP_KERNEL/blob/master/drivers/staging/android/lowmemorykiller.c#L633

**Comment by gsstudios** [comment]
Some interesting things in the log linked: 

Where all errors start to happen:
02-20 16:02:24.301 I/InputDispatcher(5098): Application is not responding: AppWindowToken{1243a5a4 token=Token{35b98c37 ActivityRecord{38217536 u0 com.teslacoilsw.launcher/.NovaLauncher t25}}} - Window{397fbdbe u0 com.teslacoilsw.launcher/com.teslacoilsw.launcher.NovaLauncher}.  It has been 5015.6ms since event, 5004.7ms since wait started.  Reason: Waiting to send key event because the focused window has not finished processing all of the input events that were previously delivered to it.  Outbound queue length: 0.  Wait queue length: 1.
02-20 16:02:24.312 I/WindowManager(5098): Input event dispatching timed out sending to com.teslacoilsw.launcher/com.teslacoilsw.launcher.NovaLauncher.  Reason: Waiting to send key event because the focused window has not finished processing all of the input events that were previously delivered to it.  Outbound queue length: 0.  Wait queue length: 1.

After freezing starts to occur:
02-20 16:02:28.783 E/ActivityManager(5098): ANR in com.teslacoilsw.launcher (com.teslacoilsw.launcher/.NovaLauncher)
02-20 16:02:28.783 E/ActivityManager(5098): PID: 16547
02-20 16:02:28.783 E/ActivityManager(5098): Reason: Input dispatching timed out (Waiting to send key event because the focused window has not finished processing all of the input events that were previously delivered to it.  Outbound queue length: 0.  Wait queue length: 1.)

After this, we get log spam:
02-20 16:02:29.240 E/Fence   (2829): GLConsumer::doGLFenceWaitLocked: fence 60 didn't signal in 3000 ms
02-20 16:02:29.240 E/GLConsumer(2829): [com.teslacoilsw.launcher/com.teslacoilsw.launcher.NovaLauncher] doGLFenceWait: error waiting for fence: -62

**Comment by Skyline96** [comment]
I have another log can i post it here?

**Comment by gsstudios** [comment]
Sure, just post the link.

**Comment by Skyline96** [comment]
Ok I can't find a way to upload log file so i have uploaded to same post at xda skyline
Check the link in your's 1st comment on this issue.
Thanks

**Comment by gsstudios** [comment]
https://github.com/gsstudios/initramfs3/commit/df66469364d61c32800c10421478e7cfebe6bed5

https://github.com/gsstudios/initramfs3/commit/e81e1af61078e8c4263e1edfeecf96c2cac82b65

Hopefully these two commits solve the problem. If it doesn't, something else is the main cause

**Comment by gsstudios** [comment]
Under some short testing, it seems that launcher FCs no longer occur. Will test for a longer period of time and report back.

**Comment by gsstudios** [comment]
Under a whole days of testing, launcher FCs no longer occur. Issue closed :)

**Comment by gsstudios** [comment]
Just updating further on the issue. It seems that after some long periods of use, FCs still occur, but they are very rare and not common. Much better than before though :)

**Comment by arny24x7** [comment]
You shudnt liv dorimanx,,,maybe update it in 6 months..but dnt liv.

**Comment by gsstudios** [comment]
When I have time, I might release some builds (EOL builds as I like to call it). I still have my build environment so hope is not lost yet :)

**Comment by gsstudios** [comment]
Reopening this issue so we can find the root cause.

**Comment by gsstudios** [comment]
Still happening with my latest test build.

**Comment by gsstudios** [comment]
Possible workaround: When using Nova Launcher, enable aggressive desktop in the settings.

**Comment by arny24x7** [comment]
Can u trace the thread from logcat while its crashing ?

**Comment by gsstudios** [comment]
I'm currently investigating whether this tweak helps or not:

https://github.com/gsstudios/Dorimanx-SG2-I9100-Kernel/commit/091e3674517771c6291337bc1d15a6ed9d9da486

**Comment by arny24x7** [comment]
I added proper bln code in lights.c. Grab the latest lights.exynos4.so from cm-13 when its compiled.

**Comment by gsstudios** [comment]
Thanks, will do so when I start working on MM kernel

**Comment by arny24x7** [comment]
lol i am already releasing my kernel for cm...I dont wanna monopolize people anymore. :-p

**Comment by gsstudios** [comment]
Just repeating my comment in the linked commit. Random Launcher FCs have been solved. :)

**Comment by gsstudios** [comment]
Random FCs still occur, although there is no more freeze now, I'll keep this open

**Comment by gsstudios** [comment]
I'm pretty sure launcher FCs don't occur in MM. LP seems to be fine also, maybe just very rare occasions, but safe enough to say that it has been fixed.
