### ISSUE TITLE
GCC 6.x support

### ISSUE THREAD

**Issue by gsstudios** [gsstudios/Dorimanx-SG2-I9100-Kernel#36]
Support GCC 6.x based toolchains

**Comment by gsstudios** [comment]
AFAIK, performance benefits will be very minor, but I'll add support just in-case I want to build using toolchains like UBER 6.0.

**Comment by chhapil** [comment]
are you using UBER TC?

On Wed, May 4, 2016 at 2:56 PM, Josh notifications@github.com wrote:

> AFAIK, performance benefits will be very minor, but I'll add support just
> in-case I want to build using toolchains like UBER 6.0.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/gsstudios/Dorimanx-SG2-I9100-Kernel/issues/36#issuecomment-216809484

## 

Thanks & Regards
Ruturaj

**Comment by gsstudios** [comment]
I am building with linaro 4.9 and UBER 5.3. But I have only selected linaro as the main toolchain. 

For gcc6.0 toolchains, I would use uber.

**Comment by gsstudios** [comment]
GCC 6.0.x toolchain support added in this commit:

https://github.com/gsstudios/Dorimanx-SG2-I9100-Kernel/commit/6257fde8171e0c74029337815099c9b0d5268e6f

No SODs after quick testing.
