### ISSUE TITLE
Add support for LineageOS/CM14.1

### ISSUE THREAD

**Issue by gsstudios** [gsstudios/Dorimanx-SG2-I9100-Kernel#75]
**PROJECT ALMOST COMPLETE**
The kernel seems to be in working order, but there are some things that need to be handled first before I deem the kernel safe for public availability. My device has shown its age so it may come to me having to do blind builds, however it would be possible for others to take a hand in development while I'm on a different device as daily driver. 

Thanks for all of the support, Josh 

**Things to do:**
- [x] Merge CM14.1 Ramdisk
- [x] Merge CM14.1 Kernel changes - All required selinux changes have been merged
- [x] Remove CM13 and CM12.1 Ramdisks - Will only support CM14.1
- [x] Figure out why the kernel bootloops (can get past dorimanx boot screen)  
- [x] Fix ROM randomly resetting back to bootscreen  
- [x] Fix broken charging (percentage is always at 100%) - Details: https://github.com/gsstudios/Dorimanx-SG2-I9100-Kernel/issues/75#issuecomment-275356976 Possible Fix: https://github.com/gsstudios/Dorimanx-SG2-I9100-Kernel/issues/75#issuecomment-306990856
- [x] Fix camera errors (camera works fine at first but after switching to video, the camera breaks) - Maybe look at this: https://github.com/LineageOS/android_kernel_samsung_smdk4412/commit/82306b193cda16ec403b81cd4dbb896a772e530c 
- [x] Fix broken cortexbrain and stweaks - Need to re-enable cortexbrain tweaks first in initramfs
- [x] Fix logcat logspam

**ETA:** Soon.

**Comment by gsstudios** [comment]
Probably not going to happen, but we'll see :)

**Comment by gsstudios** [comment]
So I've merged the ramdisk and removed support for older android versions :)

**Comment by gsstudios** [comment]
Currently the kernel just bootloops. I can get past the DorimanX kernel boot logo but that's about all I can get.

**Comment by gsstudios** [comment]
Here are the boot logs. 
[dmesg4.txt](https://github.com/gsstudios/Dorimanx-SG2-I9100-Kernel/files/725270/dmesg4.txt)
[logcat4.txt](https://github.com/gsstudios/Dorimanx-SG2-I9100-Kernel/files/725271/logcat4.txt)

Edit: Even though the init is supposed to load the file_contexts binary file, the logs throw a lot of selinux denials. I might have to convert it to a text based file. 

Edit 2: Seems that after using a text-converted file_contexts, the kernel is stuck on the DorimanX boot screen.

**Comment by Skyline96** [comment]
Is it possible to do this https://bitbucket.org/arter97/arter97-i9300-release/commits/11cbad19ea8bb74c4f07f3ec96db64f3f4014d90 ?

**Comment by gsstudios** [comment]
I have managed to get past bootscreen but the ROM is under constant crashing and goes back to bootscreen. Will investigate this soon :)

Edit: Here are the logs
[dmesg8.txt](https://github.com/gsstudios/Dorimanx-SG2-I9100-Kernel/files/728152/dmesg8.txt)
[logcat8.txt](https://github.com/gsstudios/Dorimanx-SG2-I9100-Kernel/files/728153/logcat8.txt)

Edit 2: Here are some issues I've found in the logcat:
-  F/libc    (13721): Fatal signal 6 (SIGABRT), code -6 in tid 13721 (installd) which is then followed by...
- F/DEBUG   (14418): Abort message: 'utils.cpp:67] Check failed: is_valid_package_name(package_name) == 0 '
- No such file /sys/class/mdnie/mdnie/b_adj for reading gives *** FATAL EXCEPTION IN SYSTEM PROCESS: LiveDisplay - Probably can be fixed after giving the kernel display RGB adjustment like in LOS kernel

Honestly, my debugging skills are not great enough to pinpoint the root cause

**Comment by gsstudios** [comment]
The constant crashing has been solved! :3 Now I just have to confirm the ROM is functioning well and solve the broken charging percentage (stuck on 100%)

**Comment by gsstudios** [comment]
Here is a test build of the kernel for people who want to try. 

**NO SUPPORT WILL BE GIVEN**
This is just for people who want to help. If you flash this kernel carelessly without the intention of helping me debug issues, you will be on your own and I won't help restore your device. As for those who want to help debug, currently you __can't__ dirty flash LOS 14.1 as you will lose a lot of your device's functions. You __must__ clean flash your ROM in order to restore your device to working state.

**WARNING**
The kernel is still in its early stages of development and so expect bugs. The kernel currently has basic functionality but further development will eventually have all DorimanX kernel features. 

**HOW TO HELP**
If you experience any issues, be sure to provide a logcat and a dmesg, send them to me and I will attempt to find the root causes. 

**DOWNLOAD**
Removed. [See this post instead.](https://github.com/gsstudios/Dorimanx-SG2-I9100-Kernel/issues/75#issuecomment-307009586)

**Comment by Skyline96** [comment]
Rotation seems to work fine for me.

**Comment by gsstudios** [comment]
**BATTERY PROBLEM** 
I am having trouble seeing what is the main cause of the battery issue.

The logcat hints that it can not obtain battery stats which could be directly related to the healthd driver. I've tried using the old healthd driver used in my M kernel but it results in the same problem. Further investigation will be needed. 

**VIDEO RECORDING ISSUE** 
I haven't obtained much information from this issue yet. 

**ROTATION ISSUE**
Doesn't seem to happen anymore after I rebooted. I will have to investigate closely just in-case the problem reappears. 

**CORTEXBRAIN IS DEACTIVATED ISSUE** 
Haven't got around this yet. It could be just because I commented out the function in the init script, but I will have to check.

**Comment by Skyline96** [comment]
Did you tried reverting this commit https://github.com/gsstudios/Dorimanx-SG2-I9100-Kernel/commit/0b49d2373f0f18864e49c7cbbce2a0d9502e8a34 ?

**Comment by gsstudios** [comment]
@Skyline96 
That causes the healthd driver to pick up erratic battery stats which is supposed to be resolved with the commit. It does however detect if it is really charging or not which is not observed when using the commit. 

Here's what I've tried:
- New healthd + unknown power supply type - 100% bug
- Old healthd + unknown power supply type - 100% bug 
- New healthd + battery power supply type - Erractic battery percentage
- Old healthd + battery power supply type - Erractic battery percentage 

(Note: Old healthd was using the same 'hack' found in my M kernel in order to fix offline charging, but doesn't work on N)

I might have to retest to confirm my findings but I still need to find the root cause.

**Comment by Skyline96** [comment]
Did you already seen this its old though but no harm to see https://review.cyanogenmod.org/#/c/55029/ ? ;)
Read the comments once

**Comment by gsstudios** [comment]
@Skyline96
Interesting. 

There were more 'dock' charging commits merged in CM14.1 that should have fixed some of the healthd issues. 

These changes may very well be the cause of the crazy battery percentages and hence we now deal with our current issue.

**Comment by Skyline96** [comment]
Yes there are https://github.com/LineageOS/android_system_core/search?q=healthd&type=Commits&utf8=%E2%9C%93

**Comment by gsstudios** [comment]
@Skyline96
Those were the ones I was looking at before. 

Our issue must be ever since we switched to unknown power supply, the healthd has nothing else to select/find and is then assuming 'AlwaysPluggedDevice' hence 100% bug.

**Comment by Skyline96** [comment]
Okay. What about cortexbrain ?

**Comment by gsstudios** [comment]
As indicated in the first post, I am not running DorimanX kernel on my test device only because it doesn't allow me to charge up my device. 

I haven't found the cause of this problem, I was supposed to investigate this earlier on only to discover my phone is completely dead. It would be best for me to discontinue my efforts to bring this kernel to android N (we know we can port it but there is just too much to do).

**Comment by Skyline96** [comment]
I have 2 batteries with same problem and now S2 is really showing signs of aging and thats bad everything is over

**Comment by Realex-fire** [comment]
@gsstudios @Skyline96
Hi guys, my device is still alive, but now I can't continue development because I can't allocate time for it :( 
Most likely I will be able to resume development in the summer.

**Comment by gsstudios** [comment]
@Realex-fire, take all the time you need my friend :) 
If we do eventually fix the issues since my last test build, I may release a beta/test build, but I will only provide basic support as I don't have time to play around with the s2 anymore (UNI stuff mainly) :(

**Comment by dragonGR** [comment]
Might to handle that in weekend. We'll see. :)

**Comment by gsstudios** [comment]
To anyone who want to try to fix battery charging issues in N kernel, try reverting this commit in the kernel (or adapt changes): https://github.com/LineageOS/android_kernel_samsung_smdk4412/commit/e531c03040b9ad3a86d3b751fb47b3362d85f373. 
It is required to enumerate the battery supply type which is currently broken in this kernel. 

Figured I was missing something as switching battery type to unknown without this commit was asking for trouble ;)

Cheers, 
Josh

Edit 1: Edited OP with links to possible fixes to the issues described. Won't touch the S2 anymore so I'll leave just for reference, kay bye :)

**Comment by gsstudios** [comment]
I've took the freedom to fix the charging issues myself. Original issue (offline animation appearing one) is back, but charging is working properly now

**Comment by gsstudios** [comment]
Video recording working as well now :)

**Comment by gsstudios** [comment]
Here is another test build for people to try. I have tested for a bit now ~~(on a very old unofficial build, so don't know what to expect)~~ and I feel it is alright to release only for test purposes. More work will be done when I have time as always!

Edit 1: I've tested on latest LineageOS weekly build and it works fine! A little slow (because no ZRAM and tweaks) but definitely usable :)

**WHAT WORKS**
- Camera and Video - Works, but very slow to initialize (give it time to fire up)
- Wifi 
- Bluetooth - Not tested
- Rotation
- Charging (both online and offline, but offline charging animation will disappear after first showing)

**WHAT DOESN'T WORK**
- Stweaks not installed by default - Even when installed, not functional (see below)
- Cortexbrain service - Required for stweaks and kernel scripts. Use kernel adiutor mod or kernel adiutor for now
- Probably more I'll have to find

Edit 2: Additional bugs found include crazy battery percentage drops because of fuel gauge sensor

**NO SUPPORT WILL BE GIVEN**
This is just for people who want to help. If you flash this kernel carelessly without the intention of helping me debug issues, you will be on your own and I won't help restore your device. As for those who want to help debug, currently you __can't__ dirty flash LOS 14.1 as you will lose a lot of your device's functions. You __must__ clean flash your ROM in order to restore your device to working state.

**WARNING**
The kernel is still in its early stages of development and so expect bugs. The kernel currently has basic functionality but further development will eventually have all DorimanX kernel features. 

**HOW TO HELP**
If you experience any issues, be sure to provide a logcat and a dmesg, send them to me and I will attempt to find the root causes. 

**DOWNLOAD**
[Test kernel download (Google Drive)](https://drive.google.com/open?id=0B3ApZsjOd2bzeXdoRTk2d3dKSjA)

**Comment by Realex-fire** [comment]
Hi, guys,  ( @gsstudios @Skyline96 @dragonGR )
I analyzed our problems with a kernel and came to a conclusion - selinux and new policies of Android nougat is guilty of everything. Now services require a security lab. First of all we need to launch the post-init.sh service(Described in init.rc)(for cortexbrain service). For this purpose we need to write the rule post-init.po and to introduce it in file_context then to compile own sepolicy(reassembly of a LienageOS and pull out from there new sepolicy binary file) (source сode: https://github.com/CyanogenMod/android_device_samsung_galaxys2-common/tree/cm-14.1/selinux)

Unfortunately I have not a lot of place on rigid a disk for reassembly of LineageOS, someone from us will be able to make it? 
http://blog.csdn.net/ztguang/article/details/62237875 (guid for this)

**Comment by Realex-fire** [comment]
https://github.com/Realex-fire/android_device_samsung_galaxys2-common/commit/3630425436dfaa22e13ea555311fba8a86166cab :
This should work, 'post-init' will be permissive.

**Comment by gsstudios** [comment]
Thanks for the necessary changes @Realex-fire 
Only problem now is my current test device. As from my previous posts, my device doesn't hold charge very well and refuses to charge up on dorimanx kernel.

**Comment by Realex-fire** [comment]
I can check. I just can not assemble the ROM due to lack of disk space. I'll check when I get access to a larger hard disk.

**Comment by Skyline96** [comment]
@dragonGR can help here if he gets some time for this. I am also not able to compile rom on my system due to lack of space

**Comment by dragonGR** [comment]
Will do what i can do later today.

**Comment by dragonGR** [comment]
I've successfully built LineageOS with @Realex-fire suggested commit, will work on kernel part now to pick stuff. 

You guys want the rom zip to test ? If so I'll start uploading.

**Comment by Realex-fire** [comment]
@dragonGR 
We need a binary sepolicy and file_contexts.bin files, it is in / after installing ROM

**Comment by dragonGR** [comment]
The files: https://drive.google.com/open?id=0B94g3GF6NquLNDE5dVVaQnpoVmM

The rom zip if anyone wants it: https://www.androidfilehost.com/?fid=745425885120750747

**Comment by Realex-fire** [comment]
Yeah! cortexbrain now works ! thx @dragonGR 
But there are still many problems. Wifi and default browser not work + logcat spam

**Comment by dragonGR** [comment]
I'll investigate. About logspam i can silence the spam fest as soon as i get home from work.

**Comment by Realex-fire** [comment]
Ok, I will soon post all my changes to git

**Comment by Realex-fire** [comment]
Current kernel version: http://rgho.st/8gQlKfVnm (I will temporarily return old battery charge animation)
Main problem(logcat):
```
07-24 00:06:26.954 22286 22286 I mediacodec: @@@ mediacodecservice starting
07-24 00:06:26.954 22286 22286 W /system/bin/mediacodec: libminijail: allowing syscall: clock_gettime
07-24 00:06:26.954 22286 22286 W /system/bin/mediacodec: libminijail: allowing syscall: connect
07-24 00:06:26.954 22286 22286 W /system/bin/mediacodec: libminijail: allowing syscall: fcntl64
07-24 00:06:26.954 22286 22286 W /system/bin/mediacodec: libminijail: allowing syscall: socket
07-24 00:06:26.954 22286 22286 W /system/bin/mediacodec: libminijail: allowing syscall: writev
07-24 00:06:26.958 22286 22286 W /system/bin/mediacodec: libminijail: logging seccomp filter failures
07-24 00:06:26.958 22286 22286 E /system/bin/mediacodec: libminijail: prctl(PR_SET_SECCOMP, SECCOMP_MODE_FILTER): Invalid argument
07-24 00:06:26.959 22286 22286 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 22286 (mediacodec)
07-24 00:06:26.959  2711  2711 W         : debuggerd: handling request: pid=22286 uid=1046 gid=1006 tid=22286
07-24 00:06:27.024 22294 22294 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-24 00:06:27.024 22294 22294 F DEBUG   : LineageOS Version: '14.1-20170723-UNOFFICIAL-i9100'
07-24 00:06:27.024 22294 22294 F DEBUG   : Build fingerprint: 'samsung/GT-I9100/GT-I9100:4.1.2/JZO54K/I9100XWMS2:user/release-keys'
07-24 00:06:27.024 22294 22294 F DEBUG   : Revision: '0'
07-24 00:06:27.024 22294 22294 F DEBUG   : ABI: 'arm'
07-24 00:06:27.024 22294 22294 F DEBUG   : pid: 22286, tid: 22286, name: mediacodec  >>> /system/bin/mediacodec <<<
07-24 00:06:27.024 22294 22294 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
07-24 00:06:27.024 22294 22294 F DEBUG   :     r0 00000000  r1 0000570e  r2 00000006  r3 00000008
07-24 00:06:27.024 22294 22294 F DEBUG   :     r4 b6f6e58c  r5 00000006  r6 b6f6e534  r7 0000010c
07-24 00:06:27.024 22294 22294 F DEBUG   :     r8 00000000  r9 00000000  sl 00000000  fp bed31a8c
07-24 00:06:27.024 22294 22294 F DEBUG   :     ip 00000016  sp bed319c8  lr b6a271e7  pc b6a29a50  cpsr 600f0010
07-24 00:06:27.036 22294 22294 F DEBUG   : 
07-24 00:06:27.036 22294 22294 F DEBUG   : backtrace:
07-24 00:06:27.036 22294 22294 F DEBUG   :     #00 pc 0004aa50  /system/lib/libc.so (tgkill+12)
07-24 00:06:27.036 22294 22294 F DEBUG   :     #01 pc 000481e3  /system/lib/libc.so (pthread_kill+34)
07-24 00:06:27.037 22294 22294 F DEBUG   :     #02 pc 0001d825  /system/lib/libc.so (raise+10)
07-24 00:06:27.037 22294 22294 F DEBUG   :     #03 pc 00019371  /system/lib/libc.so (__libc_android_abort+34)
07-24 00:06:27.037 22294 22294 F DEBUG   :     #04 pc 00017118  /system/lib/libc.so (abort+4)
07-24 00:06:27.037 22294 22294 F DEBUG   :     #05 pc 00005dd1  /system/lib/libminijail.so (set_seccomp_filter+132)
07-24 00:06:27.037 22294 22294 F DEBUG   :     #06 pc 00005f7d  /system/lib/libminijail.so (minijail_enter+404)
07-24 00:06:27.037 22294 22294 F DEBUG   :     #07 pc 00001031  /system/bin/mediacodec
07-24 00:06:27.037 22294 22294 F DEBUG   :     #08 pc 00000e2f  /system/bin/mediacodec
07-24 00:06:27.037 22294 22294 F DEBUG   :     #09 pc 00016c91  /system/lib/libc.so (__libc_init+48)
07-24 00:06:27.037 22294 22294 F DEBUG   :     #10 pc 00000d30  /system/bin/mediacodec
07-24 00:06:27.051 22287 22287 V MediaUtils: physMem: 843714560
07-24 00:06:27.051 22287 22287 V MediaUtils: requested limit: 168742900
07-24 00:06:27.051 22287 22287 V MediaUtils: actual limit: 168742900
07-24 00:06:27.051 22287 22287 V MediaUtils: original limits: 4294967295/4294967295
07-24 00:06:27.051 22287 22287 V MediaUtils: new limits: 168742900/4294967295
```

**Comment by Skyline96** [comment]
This seems good. Thanks @dragonGR and @Realex-fire.
Take a look here https://sourceforge.net/p/android-x86/kernel/ci/a49dcf2e745c25a67a76d8a1e9658c16827c9885/

Edit: Hey, What's wrong with wifi? I think it was to working before, afaik.

**Comment by dragonGR** [comment]
Just returned home. Thanks @Skyline96 and @Realex-fire . 

seccomp was recently introduced in android N even tho is around in linux land years years ago, will enable the flags and see.

**Comment by Skyline96** [comment]
@dragonGR plz don't forget to report result here if you get time to test changes ;)

**Comment by Realex-fire** [comment]
Inclusion of these parameters did not work, mediacodec still falls with the same error :(

**Comment by Realex-fire** [comment]
We got full work! Thanks guys. Tomorrow all the changes will be in my git

**Comment by Realex-fire** [comment]
@gsstudios @Skyline96 @dragonGR 
We got full work! Thanks guys. Tomorrow all the changes will be in my git
LineageOS/CM14.1 support is completed! (Even the camera application is now loaded quickly :) )

Ps: Seccomp is only needed on Linux kernel >3.8

**Comment by dragonGR** [comment]
Great ! More shit to kang :D :D :D :D :D

**Comment by Skyline96** [comment]
Awesome work guys :)

**Comment by Realex-fire** [comment]
@gsstudios, I sent pull requests:
https://github.com/gsstudios/initramfs3/pull/57
https://github.com/gsstudios/Dorimanx-SG2-I9100-Kernel/pull/82

**Comment by gsstudios** [comment]
I've merged the changes @Realex-fire 
I might throw around some blind builds after I do a few changes l have planned before release.

**Comment by Realex-fire** [comment]
Ok, I find minor bug: when you first start the system with the dorimanx kernel, the crash of the telephony application. If you install the kernel already on the loaded system, then there is no such problem. In any case, the reboot solves the problem. Same problem on dorimanx cm13 kernel.

**Comment by gsstudios** [comment]
I'll release the kernel when I have time.

**Comment by gsstudios** [comment]
Thanks @Realex-fire @dragonGR @Skyline96
Without your efforts, it wouldn't have been possible to have a working kernel on LOS14. 
Kernel release is imminent, and it has been a long road to get to this point.
