### ISSUE TITLE
Support other lollipop ROMs

### ISSUE THREAD

**Issue by gsstudios** [gsstudios/Dorimanx-SG2-I9100-Kernel#9]
Lollipop kernel only supports CM12.1 based ROMs.

**Comment by gsstudios** [comment]
@lysergic-acid, If you have free time, could you please help me merge more ramdisks? 

regards, gsstudios.

**Comment by CaioSchnepper** [comment]
Will be done when I'm with time available and using my linux machine :)

**Comment by gsstudios** [comment]
Thanks LA. You're the best!

**Comment by gsstudios** [comment]
I will attempt to update the kernel ramdisk sometime late november or early december.

**Comment by gsstudios** [comment]
I don't plan to support other lollipop ROMs anymore.
